---
apiVersion: v1
kind: Service
metadata:
  name: people-db
  namespace: test-apm
  labels:
    app: people-db
spec:
  selector:
    app: people-db
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 5001
