apiVersion: v1
kind: ConfigMap
metadata:
  name: query
  namespace: test-apm
  labels:
    app: query
data:
  query_script.sh: |-
    #!/bin/sh
    count=0
    while true; do
      if [ $count == 7 ]; then
        curl test-apm-flask:5000/5xx
      fi

      div5=`expr $count % 5`
      if [ $div5 == 5 ]; then
        curl test-apm-flask:5000/delay
      fi

      div3=`expr $count % 3`
      if [ $div3 == 0 ]; then
        curl test-apm-flask:5000/sql-write
      fi

      div2=`expr $count % 2`
      if [ $div2 == 0 ]; then
        curl test-apm-flask:5000/sql-write
      fi

      curl test-apm-flask:5000
      curl test-apm-flask:5000/upstream
      curl test-apm-flask:5000/sql-read

      count=`expr $count + 1`
      count=`expr $count % 10`
      sleep 2
    done

